<a href="https://colab.research.google.com/github/ChristianIES/EstComp/blob/main/2022_EC_Tarea_1_Estad%C3%ADstica_Computacional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 1 - Estadística Computacional

- Nombre: Christian Araya M.
- Nombre: 

Curso: Estadística Computacional

Doctorado en Estadística


Responda las preguntas que se indican colocando el código requerido. El Notebook se entrega totalmente ejecutado.

**Ingrese los Toolbox que se utilizarán en este Jupyter**

In [ ]:
from scipy import stats     #para corroborar cálculo de correlación de Spearman
import numpy as np          #para construir matriz de rezagos     

## 1. Indicadores estadísticos.

En estadística, en muchas ocasiones se requiere implementar indicadores o estadísticos. En esta pregunta deberá implementar los siguientes indicadores:

1. **Symmetric mean absolute percentage error (SMAPE or sMAPE)**: es una medida de precisión basada en errores porcentuales (o relativos).

$$sMAPE = \frac{100\%}{n}\sum_{t=1}^n \frac{|F_t-A_t|}{(|A_t|+|F_t|)/2}$$

donde $A_t$ es el valor real y $F_t$ es el valor de pronóstico.

Implementar la Función sMAPE:

In [ ]:
def sMAPE(datos, predicciones):
  if len(datos)!=len(predicciones):
    print("Alerta, no se puede proceder.")
  else:
    n=len(datos)
    num=0
    den=0
    for i in range(0,n):
      num=num+abs(predicciones[i]-datos[i])
      den=den+0.5*(abs(predicciones[i]+datos[i]))
  resultado=(100/n)*num/den
  return resultado


Aplicar la función sMAPE de las siguientes listas:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }
       
Predicción = { 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5}


In [ ]:
Dato = [1.5 , 2.89, -0.08, -2.93, -1.35, 2.26, 2.47, -1.05, -2.98, -0.41, 2.78, 1.78, -1.91, -2.71, 0.58, 3. , 0.9 , -2.56, -2.15, 1.5 ]
Prediccion = [ 3.58, 4.3 , 0.5 , -3.11, -1.94, 3.71, 1.56, -1.55, -2.77, -0.51, 2.93, 2.14, -1.76, -1.96, -0.51, 2.96, -0.34, -3.33, -3.49, 1.5]
x=sMAPE(Dato,Prediccion)
print("El valor de SMAPE corresponde a: ",round(x,2),"%")

El valor de SMAPE corresponde a:  1.73 %


2. **Coeficiente de correlación de Spearman ($\rho$)**: es una medida de la correlación (la asociación o interdependencia) entre dos variables aleatorias (tanto continuas como discretas). Para calcular $\rho$, los datos son ordenados y reemplazados por su respectivo orden.

El estadístico está dado por:

$$\rho = 1 - \frac{6\sum_i D_{(i)}^2}{N(N^2-1)}$$

donde $D_{(i)}$ es la diferencia entre los correspondientes estadísticos de orden de $x$ e $y$. $N$ es el número de parejas de datos.


In [ ]:
#Para ordenar con método burbuja:

def OrdenarBurbuja(set1):
  flag = True
  n=len(set1)
  while flag:
      flag=False
      for i in range(0,n-1):
        if set1[i]>set1[i+1]:
          aux=set1[i]
          set1[i]=set1[i+1]
          set1[i+1]=aux
          flag=True
          #print(set1)
  return set1



In [ ]:
#Para encontrar los estadísticos de orden (no utilizada en la versión final):

def EstOrden(datos):
  estadisticos=[]
  ordenado=datos.copy()
  ordenado=ordenarBurbuja(ordenado)
  indice=1
  for i in datos:
    for j in range(0,len(ordenado)-1):
      if i==ordenado[j]:
        estadisticos.append(indice)
        indice+=1
  return estadisticos


In [ ]:
  #Para promediar los rangos de los datos repetidos:
  
  def Correccion(datos,datosordenados):
    result=[0]*len(datos)
    for j in range(0, len(datos)):
      contador=0
      sum=0
      for k in range(0, len(datosordenados)):
        if datos[j]==datosordenados[k]:
          sum=sum+(k+1)
          contador+=1
      result[j]=(sum/contador)
    return result


In [ ]:
#Para calcular la correlación de Spearman:

def Spearman(dato1,dato2):
  dato1O=OrdenarBurbuja(dato1)
  dato2O=OrdenarBurbuja(dato2)
  dic1=dict(zip(dato1O, Correccion(dato1,dato1O)))
  dic2=dict(zip(dato2O, Correccion(dato2,dato2O)))
  print(dic1)
  print(dic2)
  if len(dato1)!=len(dato2):
    print("Se requieren sets de datos del mismo tamaño.")
  else:
    n=len(dato1)
    suma=0
    for i in range(0,n):
      suma=suma+(dic1[dato1[i]]-dic2[dato2[i]])**2
    coef=1-6*(suma)/(n*(n**2-1))
  return round(coef,3)

Calcular el coeficiente de correlación de Spearman para los siguientes datos:
    
Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }
       
Predicción = { 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5}

In [ ]:
Dato=[1.5,2.89,-0.08,-2.93,-1.35,2.26,2.47,-1.05,-2.98,-0.41,2.78,1.78,-1.91,-2.71,0.58,3.,0.9,-2.56,-2.15,1.5]
Prediccion=[3.58,4.3,0.5,-3.11,-1.94,3.71,1.56,-1.55,-2.77,-0.51,2.93,2.14,-1.76,-1.96,-0.51,2.96,-0.34,-3.33,-3.49,1.5]
x=Spearman(Dato,Prediccion)
print("La correlación de Spearman es (redondeada a 3 decimales): ", x)


#----------------------
#t=OrdenarBurbuja(Dato)
#print(t)
#e=EstOrden(t)
#print(e)
#Correccion(Dato,t)


{-2.98: 1.0, -2.93: 2.0, -2.71: 3.0, -2.56: 4.0, -2.15: 5.0, -1.91: 6.0, -1.35: 7.0, -1.05: 8.0, -0.41: 9.0, -0.08: 10.0, 0.58: 11.0, 0.9: 12.0, 1.5: 13.5, 1.78: 15.0, 2.26: 16.0, 2.47: 17.0, 2.78: 18.0, 2.89: 19.0, 3.0: 20.0}
{-3.49: 1.0, -3.33: 2.0, -3.11: 3.0, -2.77: 4.0, -1.96: 5.0, -1.94: 6.0, -1.76: 7.0, -1.55: 8.0, -0.51: 9.5, -0.34: 11.0, 0.5: 12.0, 1.5: 13.0, 1.56: 14.0, 2.14: 15.0, 2.93: 16.0, 2.96: 17.0, 3.58: 18.0, 3.71: 19.0, 4.3: 20.0}
La correlación de Spearman es (redondeada a 3 decimales):  0.999


3. **Coeficiente de Gini:** es una medida de la desigualdad. El coeficiente de Gini es un número entre 0 y 1, en donde 0 se corresponde con la perfecta igualdad (todos tienen los mismos ingresos) y donde el valor 1 se corresponde con la perfecta desigualdad. Para obtener el coeficiente de Gini, en general se utiliza la fórmila de Brown:

$$G = \left|1 - \sum_{k=1}^n (X_{k+1}-X_k)(Y_{k+1}+Y_k)\right|$$

donde $X$ e $Y$ corresponden a la proporción acumulada de las variables.

Implementar la función que calcule el coeficiente de Gini.


In [ ]:
def Gini(X,Y):
  if len(X)!=len(Y):
    print("Alerta, debe ingresar la misma cantidad de datos para ambas variables.")
  else:
    n=len(X)
    sum=0
    for i in range(0,n-1):
      sum=sum+(X[i+1]-X[i])*(Y[i+1]+Y[i])
  coeficiente=abs(1-sum)
  return coeficiente

Obtener el coeficiente de Gini para las siguientes dos proporciones:

| Variables Acumuladas| Clase 1 | Clase 2 | Clase 3 | Clase 4 | Clase 5 |
| --- | --- | --- | --- | --- | --- |
| X | 0.09 | 0.33 | 0.45 | 0.78 | 1 |
| Y | 0.17 | 0.48 | 0.62 | 0.86 | 1 |



In [ ]:
X=[0.09,0.33,0.45,0.78,1]
Y=[0.17,0.48,0.62,0.86,1]
resultado=Gini(X,Y)
print("El coeficiente de Gini para los datos ingresados es: ",round(resultado,2))

El coeficiente de Gini para los datos ingresados es:  0.19


## 2. Algoritmos

1. Dado dos conjuntos de datos ordenados y de tamaños diferentes, realizar una función que mezcle ambos conjunto y genere un nuevo conjunto con todos los datos ordenados.

In [ ]:
def mezclarordenar(set1,set2):
  union=set1.union(set2)
  union=list(union)
  #print(union)
  flag = True
  while flag:
      flag = False
      for i in range(0,len(union)-1):
        if union[i]>=union[i+1]:
          aux=union[i]
          union[i]=union[i+1]
          union[i+1]=aux
          flag = True
          #print(union)
  return set(union)

  #Importante: si hay elementos repetidos en los conjuntos, estos aparecerán
  #1 vez en el conjunto final, dado que se está utilizando la operación de unión
  #para la estructura de tipo conjunto.

Aplicar el algoritmo para mezclar y ordenar los siguientes conjuntos:

$$D_1 = \{5, 7, 15, 23, 45, 72, 83\}$$

$$D_2= \{1, 2, 6, 29, 37, 75, 100, 110, 115, 117\}$$

In [ ]:
D1={5,7,15,23,45,72,83} 
D2={1,2,6,29,37,75,100,110,115,117} 
mezclarordenar(D1,D2)

{1, 2, 5, 6, 7, 15, 23, 29, 37, 45, 72, 75, 83, 100, 110, 115, 117}

2. La equivalencia de los símbolos básicos de los números romanos es la siguiente:

|Número Romano | I | V | X | L | C | D | M |
| --- | --- | --- | --- | --- | --- | --- | --- |
|Número decimal| 1 | 5 | 10 | 50 | 100 | 500 | 1000 |

Los enteros romanos se escriben de acuerdo a las siguientes reglas:

- Si una letra está seguida inmediatamente por una de igual o menor valor, su valor se suma al total acumulado. Así, XX = 20, XV = 15 y VI = 6.
- Si una letra está seguida inmediatamente por una de mayor valor, su valor se sustrae del total acumulado. Así, IV = 4, XL = 40 y CM = 900.

Escriba la función que reciba un string con un número en notación romana, y entregue el entero equivalente:

In [ ]:
diccionario_base={'I': 1, 'V': 5, 'X': 10,'L': 50, 'C': 100, 'D': 500, 'M': 1000}

def romanoAindoar(texto):
  casilla=0
  total=0
  anterior=0
  for j in texto[::-1]:
    casilla=diccionario_base[j]
    if casilla >= anterior:
      total=total+casilla
    else:
      total=total-casilla
    anterior=casilla
  return total



In [ ]:
t=input("Ingrese un número romano: ")
print("El número que ingreso corresponde a: ", romanoAindoar(t))

Ingrese un número romano: MCMXCIX
El número que ingreso corresponde a:  1999


## 3. Algoritmos en Series de Tiempo

Una serie de tiempo es una secuencia de valores numéricos obtenidos a intervalos de tiempos regulares.

$$X=\{x_1, x_2,....., x_t, ..., x_T\}$$

1. Las medias móviles con retardo $p$ de una serie de tiempo son las secuencia de todos los promedios de $p$ valores consecutivos de la serie. Realizar una función que retorne el arreglo de las medias móviles con retardo $p$ de la serie.

In [ ]:
def medias_mov(dato,p):
  medias=[]
  indice=0
  suma=0
  cuenta=0
  for i in range(0,len(dato)):
    suma=suma+dato[i]
    #print(dato[i])
    cuenta=cuenta+1
    if cuenta%p==0:
      medias.append(round(suma/p,3))
      suma=0
  return medias    

#en caso de que el largo de la lista de datos no sea múltiplo de "p",
#la función exhibe hasta la última media calculada con "p" elementos,
#omitiendo aquellos que "sobraron" (son menos de "p" elementos).


Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [ ]:
Dato = [1.5,2.89,-0.08,-2.93,-1.35,2.26,2.47,-1.05,-2.98,-0.41,2.78,1.78,-1.91,-2.71,0.58,3.,0.9,-2.56,-2.15,1.5]
medias_mov(Dato,4)

[0.345, 0.583, 0.292, -0.26, -0.578]

2. Las diferencias finitas de una serie de tiempo son la secuencia de todas las diferencias entre un valor y el anterior. Escribir una función que retorne el arreglo de las diferencias finitas de la serie.

In [ ]:
def dif_finitas(dato):
  resultado=[]
  for i in range(0,len(dato)-1):
    resultado.append(round(dato[i+1]-dato[i],3))
    #print(dato[i])
    #cuenta=cuenta+1
  return resultado 

Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [ ]:
Dato = [1.5,2.89,-0.08,-2.93,-1.35,2.26,2.47,-1.05,-2.98,-0.41,2.78,1.78,-1.91,-2.71,0.58,3. ,0.9 ,-2.56,-2.15,1.5]
dif_finitas(Dato)

[1.39,
 -2.97,
 -2.85,
 1.58,
 3.61,
 0.21,
 -3.52,
 -1.93,
 2.57,
 3.19,
 -1.0,
 -3.69,
 -0.8,
 3.29,
 2.42,
 -2.1,
 -3.46,
 0.41,
 3.65]

3. En algunos métodos se requiere construir la matriz de rezagos de orden p. Esto es, dado la serie de tiempo:

$$X=\{x_1, x_2,....., x_t, ..., x_T\}$$

La matriz de rezagos de orden $p$ está dada por:

$$M = \left[\begin{array}{cccccc}
x_1 & x_2 & ... & x_p\\
x_2 & x_3 & ... & x_{p+1}\\
x_4 & x_5 & ... & x_{p+2}\\
... & ... & ... & ...\\
x_{T-p} & x_{T-p+1} & ... & x_{T-1}\\
x_{T-p+1} & x_{T-p+2} & ... & x_{T}\\
\end{array}
\right]$$ 

Realizar una función que construya dicha estructura de datos.

In [ ]:
def MatrizRezagos(datos,p):
  T=len(datos)-p+1
  matriz=np.zeros((T, p))
  indice=0
  for i in range(0,T):
    for j in range(0,p):
      matriz[i,j]=datos[indice+j]
    indice+=1
  return matriz

Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [ ]:
Dato=[1.5,2.89,-0.08,-2.93,-1.35,2.26,2.47,-1.05,-2.98,-0.41,2.78,1.78,-1.91,-2.71,0.58,3.,0.9,-2.56,-2.15,1.5]
p=int(input("Ingrese 'p' entero para obtener matriz de rezagos: "))
m=MatrizRezagos(Dato,p)
print(m)

Ingrese 'p' entero para obtener matriz de rezagos: 3
[[ 1.5   2.89 -0.08]
 [ 2.89 -0.08 -2.93]
 [-0.08 -2.93 -1.35]
 [-2.93 -1.35  2.26]
 [-1.35  2.26  2.47]
 [ 2.26  2.47 -1.05]
 [ 2.47 -1.05 -2.98]
 [-1.05 -2.98 -0.41]
 [-2.98 -0.41  2.78]
 [-0.41  2.78  1.78]
 [ 2.78  1.78 -1.91]
 [ 1.78 -1.91 -2.71]
 [-1.91 -2.71  0.58]
 [-2.71  0.58  3.  ]
 [ 0.58  3.    0.9 ]
 [ 3.    0.9  -2.56]
 [ 0.9  -2.56 -2.15]
 [-2.56 -2.15  1.5 ]]
